#!/bin/bash
mkdir -p temp_audio

echo "Downloading songs..."
yt-dlp -x --audio-format mp3 -o "temp_audio/Starboy.%(ext)s" "https://www.youtube.com/watch?v=34Na4j8HLjc"
yt-dlp -x --audio-format mp3 -o "temp_audio/Save_Your_Tears.%(ext)s" "https://www.youtube.com/watch?v=XXYlFuWEuKI"
yt-dlp -x --audio-format mp3 -o "temp_audio/Lover.%(ext)s" "https://www.youtube.com/watch?v=-BjZmE2gtdo"
yt-dlp -x --audio-format mp3 -o "temp_audio/Anti_Hero.%(ext)s" "https://www.youtube.com/watch?v=b1kbLwvqugk"
yt-dlp -x --audio-format mp3 -o "temp_audio/Nice_For_What.%(ext)s" "https://www.youtube.com/watch?v=UceaB4D0jqw"
yt-dlp -x --audio-format mp3 -o "temp_audio/Hotline_Bling.%(ext)s" "https://www.youtube.com/watch?v=uxpDa-c-4Mc"
yt-dlp -x --audio-format mp3 -o "temp_audio/Bury_A_Friend.%(ext)s" "https://www.youtube.com/watch?v=HUHC9tMqzcg"
yt-dlp -x --audio-format mp3 -o "temp_audio/Therefore_I_Am.%(ext)s" "https://www.youtube.com/watch?v=RUQl6YcMsho"
yt-dlp -x --audio-format mp3 -o "temp_audio/Circles.%(ext)s" "https://www.youtube.com/watch?v=wXhTHyIgQ_U"
yt-dlp -x --audio-format mp3 -o "temp_audio/Without_Me.%(ext)s" "https://www.youtube.com/watch?v=YVkUvmDQ3HY"
yt-dlp -x --audio-format mp3 -o "temp_audio/Superman.%(ext)s" "https://www.youtube.com/watch?v=8kYkciD9VjU"
yt-dlp -x --audio-format mp3 -o "temp_audio/Levitating.%(ext)s" "https://www.youtube.com/watch?v=TUVcZfQe-Kw"
yt-dlp -x --audio-format mp3 -o "temp_audio/Dont_Start_Now.%(ext)s" "https://www.youtube.com/watch?v=oygrmJFKYZY"
yt-dlp -x --audio-format mp3 -o "temp_audio/Shape_Of_You.%(ext)s" "https://www.youtube.com/watch?v=JGwWNGJdvx8"
yt-dlp -x --audio-format mp3 -o "temp_audio/Perfect.%(ext)s" "https://www.youtube.com/watch?v=2Vv-BfVoq4g"
yt-dlp -x --audio-format mp3 -o "temp_audio/7_rings.%(ext)s" "https://www.youtube.com/watch?v=QYh6mYIJG2Y"
yt-dlp -x --audio-format mp3 -o "temp_audio/thank_u_next.%(ext)s" "https://www.youtube.com/watch?v=gl1aHhXnN1k"
yt-dlp -x --audio-format mp3 -o "temp_audio/Thats_What_I_Like.%(ext)s" "https://www.youtube.com/watch?v=PMivT7MJ41M"
yt-dlp -x --audio-format mp3 -o "temp_audio/Locked_Out_Of_Heaven.%(ext)s" "https://www.youtube.com/watch?v=e-fA-gBCkj0"

echo "Downloading placeholder images for remaining artists and covers..."
# 5 new artists profile pics
curl -s -L -o "temp_audio/eminem.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/dualipa.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/edsheeran.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/arianagrande.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/brunomars.jpg" "https://picsum.photos/400"

# Covers for new songs
curl -s -L -o "temp_audio/starboy_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/saveyourtears_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/lover_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/antihero_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/niceforwhat_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/hotlinebling_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/buryafriend_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/thereforeiam_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/circles_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/withoutme_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/superman_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/levitating_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/dontstartnow_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/shapeofyou_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/perfect_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/7rings_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/thankunext_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/thatswhatilike_cover.jpg" "https://picsum.photos/400"
curl -s -L -o "temp_audio/lockedoutofheaven_cover.jpg" "https://picsum.photos/400"

echo "Done downloading"
